name: .NET MAUI CI Build 

on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
permissions:
  contents: read

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-windows:
    runs-on: windows-latest
    name: Windows Build
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET Core 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        include-prerelease: true

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: true

    - name: Install MAUI Workloads
      run: | 
        dotnet workload install maui --ignore-failed-sources
          
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build MAUI Windows
      run: msbuild WorkScheduleReminder.MAUIBlazor/WorkScheduleReminder.MAUIBlazor.csproj -r -p:Configuration=Release -p:RestorePackages=false  -p:TargetFrameworks=net7.0-windows10.0.19041.0;net7.0
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    


        
