name: .NET MAUI CI Build 

on:
  push        :
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  
jobs:
  install-environment:
    runs-on: windows-latest
    name   : Install Environment
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4.1.1
      -
        name: Setup .NET Core 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      -
        name: Setup JDK 11
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '11'
      -
        name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
      -
        name: Install MAUI Workloads
        run : | 
          dotnet workload install maui --ignore-failed-sources
      -
        name: Install Chocolatey (Windows Package Manager)
        uses: crazy-max/ghaction-chocolatey@v3.0.0
        with:
          args: -h  
      -
        name: Install Edge Webview2 Runtime
        run : |
          choco install webview2-runtime
          
  build-maui-desktop-app-on-windows-platform:
    runs-on: windows-latest
    name   : Build MAUI Desktop App On Windows Platform
    needs: install-environment
    steps:          
      - 
        name: Restore dependencies
        run : |
          dotnet restore
      -
        name: Build
        working-directory: ./WorkScheduleReminder.MAUIBlazor
        run : |
          msbuild WorkScheduleReminder.MAUIBlazor.csproj -r -p:Configuration=Debug -p:RestorePackages=false

  test:
    runs-on: windows-latest
    name   : Testing
    needs: build-maui-desktop-app-on-windows-platform
    steps:
      -
        name: Test
        run : |
          dotnet test --verbosity normal

    


        
